# Generated by Django 4.2.3 on 2023-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=11)),
                ('parent_number', models.CharField(max_length=11)),
                ('academic_year', models.CharField(max_length=50)),
            ],
        ),
    ]
